// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  admin: dynamic(() => import("./Admin")),
  hero: dynamic(() => import("./Hero")),
};
